site_name: NYC Taxi Data Pipeline
site_name: NYC Taxi Data Pipeline
site_author: "Mezine Elias"
site_url: https://eliasmez.github.io/nyc-taxi-pipeline/
repo_url: https://github.com/EliasMez/nyc-taxi-pipeline/
repo_name: nyc-taxi-pipeline
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - i18n:
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: fr
          name: FranÃ§ais
          build: true
          nav:
            - ğŸš• Accueil: index.md
            - ğŸ›ï¸ Architecture: architecture.md
            - ğŸ“ˆ Gouvernance: governance.md
            - ğŸš€ ExÃ©cution: execution.md
            - ğŸ“š Docstrings: docstrings.md
        - locale: es
          name: EspaÃ±ol
          build: true
          nav:
            - ğŸš• Inicio: index.md
            - ğŸ›ï¸ Arquitectura: architecture.md
            - ğŸ“ˆ Gobernanza: governance.md
            - ğŸš€ EjecuciÃ³n: execution.md
            - ğŸ“š Docstrings: docstrings.md
        - locale: zh
          name: ä¸­æ–‡
          build: true
          nav:
            - ğŸš• ä¸»é¡µ: index.md
            - ğŸ›ï¸ æ¶æ„: architecture.md
            - ğŸ“ˆ æ²»ç†: governance.md
            - ğŸš€ æ‰§è¡Œ: execution.md
            - ğŸ“š æ–‡æ¡£å­—ç¬¦ä¸²: docstrings.md
        - locale: "null"
          name: "dbt docs"
          build: false
          fixed_link: https://eliasmez.github.io/nyc-taxi-pipeline/dbt/
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            heading_level: 3

nav:
  - ğŸš• Accueil: index.md
  - ğŸ›ï¸ Architecture: architecture.md
  - ğŸ“ˆ Governance: governance.md
  - ğŸš€ Execution: execution.md
  - ğŸ“š Docstrings: docstrings.md