name: NYC Taxi Data Pipeline

on:
  schedule:
    - cron: '0 10 1 * *'
      branches:
        - main
  workflow_dispatch:

jobs:
  load-taxi-data:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      USER_DEV: ${{ vars.USER_DEV || 'USER_DEV' }}
      USER_BI: ${{ vars.USER_BI || 'USER_BI' }}
      USER_DS: ${{ vars.USER_DS || 'USER_DS' }}
      USER_MC: ${{ vars.USER_MC || 'USER_MC' }}
      SCRAPING_YEAR: ${{ vars.SCRAPING_YEAR }}
      LOGGER_LEVEL: ${{ vars.LOGGER_LEVEL || 'INFO' }}
      WH_NAME: ${{ vars.WH_NAME || 'NYC_WH' }}
      DW_NAME: ${{ vars.DW_NAME || 'NYC_TAXI_DW' }}
      RAW_SCHEMA: ${{ vars.RAW_SCHEMA || 'RAW' }}
      STAGING_SCHEMA: ${{ vars.STAGING_SCHEMA || 'STAGING' }}
      FINAL_SCHEMA: ${{ vars.FINAL_SCHEMA || 'FINAL' }}
      PARQUET_FORMAT: ${{ vars.PARQUET_FORMAT || 'PARQUET_FORMAT' }}
      ID_SEQUENCE: ${{ vars.ID_SEQUENCE || 'TRIP_ID_SEQ' }}
      COMPUTE_SIZE: ${{ vars.COMPUTE_SIZE || 'X-SMALL' }}
      ROLE_TRANSFORMER: ${{ vars.ROLE_TRANSFORMER || 'TRANSFORMER' }}
      ROLE_BI_ANALYST: ${{ vars.ROLE_BI_ANALYST || 'BI_ANALYST' }}
      ROLE_DATA_SCIENTIST: ${{ vars.ROLE_DATA_SCIENTIST || 'DATA_SCIENTIST' }}
      ROLE_MART_CONSUMER: ${{ vars.ROLE_MART_CONSUMER || 'MART_CONSUMER' }}
      PASSWORD_DEV: ${{ secrets.PASSWORD_DEV }}
      PASSWORD_BI: ${{ secrets.PASSWORD_BI }}
      PASSWORD_DS: ${{ secrets.PASSWORD_DS }}
      PASSWORD_MC: ${{ secrets.PASSWORD_MC }}
      METADATA_TABLE: ${{ vars.METADATA_TABLE || 'FILE_LOADING_METADATA' }}
      RAW_TABLE: ${{ vars.RAW_TABLE || 'YELLOW_TAXI_TRIPS_RAW' }}
      STAGING_TABLE: ${{ vars.STAGING_TABLE || 'YELLOW_TAXI_TRIPS_STG' }}
      TIMEZONE: ${{ vars.TIMEZONE || 'UTC' }}
      RETENTION_TIME: ${{ vars.RETENTION_TIME || '1' }}
      FULL_BACKUP_POLICY_DAYS: ${{ vars.FULL_BACKUP_POLICY_DAYS || '180' }}
      RAW_TABLE_BACKUP_POLICY_DAYS: ${{ vars.RAW_TABLE_BACKUP_POLICY_DAYS || '730' }}
      FINAL_SCHEMA_BACKUP_POLICY_DAYS: ${{ vars.FINAL_SCHEMA_BACKUP_POLICY_DAYS || '90' }}
      AWS_EC2_METADATA_DISABLED: true
      
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5
      
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Modules
      run: pip install -e .

    - name: Snowflake Infra Init
      run: |
        python -m snowflake_ingestion.init_infra_snowflake

    - name: Scrape Links
      run: |
        python -m snowflake_ingestion.scrape_links

    - name: Upload to Stage
      run: |
        python -m snowflake_ingestion.upload_stage

    - name: Load to Table
      run: |
        python -m snowflake_ingestion.load_to_table

    - name: Install dbt Dependencies
      run: |
        dbt deps --project-dir dbt_transformations/NYC_Taxi_dbt --profiles-dir dbt_transformations
        dbt seed --project-dir dbt_transformations/NYC_Taxi_dbt --profiles-dir dbt_transformations

    - name: Run dbt Transformations
      run: |
        dbt run --project-dir dbt_transformations/NYC_Taxi_dbt --profiles-dir dbt_transformations

    - name: Run dbt Tests
      run: |
        dbt test --project-dir dbt_transformations/NYC_Taxi_dbt --profiles-dir dbt_transformations

    - name: Set Backup
      run: |
        python -m snowflake_ingestion.backup_policy
    
