name: Python Code Tests
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      PASSWORD_DEV: ${{ secrets.PASSWORD_DEV }}
      SCRAPING_YEAR: ${{ vars.SCRAPING_YEAR }}
      LOGGER_LEVEL: ${{ vars.LOGGER_LEVEL || 'INFO' }}
      WH_NAME: ${{ vars.WH_NAME || 'NYC_WH' }}
      DW_NAME: ${{ vars.DW_NAME || 'NYC_TAXI_DW' }}
      RAW_SCHEMA: ${{ vars.RAW_SCHEMA || 'SCHEMA_RAW' }}
      PARQUET_FORMAT: ${{ vars.PARQUET_FORMAT || 'PARQUET_FORMAT' }}
      ROLE_TRANSFORMER: ${{ vars.ROLE_TRANSFORMER || 'TRANSFORMER' }}
      USER_DEV: ${{ vars.USER_DEV || 'USER_DEV' }}
      METADATA_TABLE: ${{ vars.METADATA_TABLE || 'FILE_LOADING_METADATA' }}
      RAW_TABLE: ${{ vars.RAW_TABLE || 'YELLOW_TAXI_TRIPS_RAW' }}


    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Python Tests
        run: pytest snowflake_ingestion/tests/ -v