name: SQL Code Quality
on:
  push:
    branches: [ dev ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  lint-snowflake:
    name: Lint Snowflake SQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install SQLFluff
        run: pip install sqlfluff
      
      - name: Lint Snowflake SQL
        run: sqlfluff lint snowflake_ingestion/sql/ --config .sqlfluff

  lint-dbt:
    name: Lint dbt SQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install SQLFluff
        run: pip install sqlfluff
      
      - name: Lint dbt models
        run: sqlfluff lint dbt_transformations/NYC_Taxi_dbt/models/ --config .sqlfluff